# Generated by Django 5.2.14 on 2026-07-04 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#8b5cf6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'brochure categories',
                'db_table': 'brochure_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.TextField()),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('file_name', models.TextField(blank=True, default='')),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_brochures', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_brochures', to=settings.AUTH_USER_MODEL)),
                ('category_ref', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochures', to='brochures.brochurecategory')),
            ],
            options={
                'db_table': 'brochures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrochureSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brochure_id', models.TextField()),
                ('brochure_title', models.TextField(blank=True, default='')),
                ('brochure_data', models.JSONField(blank=True, default=dict)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mr', models.ForeignKey(db_column='mr_id', on_delete=django.db.models.deletion.CASCADE, related_name='brochure_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brochure_sync',
                'unique_together': {('mr', 'brochure_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedBrochure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brochure_id', models.TextField()),
                ('brochure_title', models.TextField(blank=True, default='')),
                ('custom_title', models.TextField(blank=True, default='')),
                ('original_brochure_data', models.JSONField(blank=True, default=dict)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mr', models.ForeignKey(db_column='mr_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_brochures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_brochures',
                'unique_together': {('mr', 'brochure_id')},
            },
        ),
    ]
