# Generated by Django 5.2.15 on 2026-07-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0003_allow_multiple_saved_copies'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedbrochure',
            new_name='saved_broch_mr_id_61c50d_idx',
            old_name='saved_broch_mr_broch_idx',
        ),
    ]
