# Generated by Django 5.2.14 on 2026-07-04 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brochures', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('active', 'Active')], default='scheduled', max_length=20)),
                ('location', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_time', models.TextField(blank=True, default='')),
                ('follow_up_notes', models.TextField(blank=True, default='')),
                ('presentation_slides', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brochure', models.ForeignKey(blank=True, db_column='brochure_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='brochures.brochure')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='doctors.doctor')),
                ('mr', models.ForeignKey(db_column='mr_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_up_date', models.DateTimeField()),
                ('follow_up_time', models.TextField(blank=True, default='')),
                ('follow_up_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sequence_number', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_followups',
                'ordering': ['sequence_number', 'follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSlideNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slide_id', models.TextField()),
                ('slide_title', models.TextField(blank=True, default='')),
                ('slide_order', models.IntegerField(default=0)),
                ('brochure_id', models.TextField(blank=True, default='')),
                ('note_text', models.TextField(blank=True, default='')),
                ('slide_image_uri', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, related_name='slide_notes', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_slide_notes',
                'ordering': ['slide_order', 'created_at'],
            },
        ),
    ]
