from django.urls import path

from accounts.views.mr_views import (
    MRBrochureListView,
    MRBrochureSyncDetailView,
    MRBrochureSyncView,
    MRBrochureUploadView,
    MRDashboardStatsView,
    MRDoctorAssignmentView,
    MRDoctorListView,
    MRFollowUpDetailView,
    MRLegacyFollowUpView,
    MRMeetingDetailView,
    MRMeetingFollowUpListView,
    MRMeetingListView,
    MRMeetingNoteDetailView,
    MRMeetingNotesView,
    MRPerformanceSummaryView,
    MRPresentationsView,
    MRRecentActivitiesView,
    MRSavedBrochureDetailView,
    MRSavedBrochureView,
    MRUpcomingMeetingsView,
)

urlpatterns = [
    path("dashboard/stats/", MRDashboardStatsView.as_view()),
    path("dashboard/activities/", MRRecentActivitiesView.as_view()),
    path("dashboard/performance/", MRPerformanceSummaryView.as_view()),
    path("brochures/", MRBrochureListView.as_view()),
    path("brochures/upload/", MRBrochureUploadView.as_view()),
    path("presentations/", MRPresentationsView.as_view()),
    path("doctors/", MRDoctorListView.as_view()),
    path("doctor-assignments/", MRDoctorAssignmentView.as_view()),
    path("doctor-assignments/<uuid:pk>/", MRDoctorAssignmentView.as_view()),
    path("meetings/", MRMeetingListView.as_view()),
    path("meetings/upcoming/", MRUpcomingMeetingsView.as_view()),
    path("meetings/<uuid:pk>/", MRMeetingDetailView.as_view()),
    path("meetings/<uuid:pk>/notes/", MRMeetingNotesView.as_view()),
    path("meetings/<uuid:pk>/notes/<uuid:note_id>/", MRMeetingNoteDetailView.as_view()),
    path("meetings/<uuid:pk>/followups/", MRMeetingFollowUpListView.as_view()),
    path("meetings/<uuid:pk>/followup/", MRLegacyFollowUpView.as_view()),
    path("followups/<uuid:pk>/", MRFollowUpDetailView.as_view()),
    path("saved-brochures/", MRSavedBrochureView.as_view()),
    path("saved-brochures/<uuid:pk>/", MRSavedBrochureDetailView.as_view()),
    path("brochure-sync/", MRBrochureSyncView.as_view()),
    path("brochure-sync/<str:brochure_id>/", MRBrochureSyncDetailView.as_view()),
]
